name: Test Secrets
on:
  workflow_dispatch:
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check WAKATIME_API_KEY
        env:  # Define the environment for this step
          WAKATIME_API_KEY: waka_fb60903e-3fe8-4053-b437-5cac63fe8aeb # Assign the secret to an env variable
        run: |
          curl -X GET "https://wakatime.com/api/v1/users/current/stats/last_7_days" \
          -H "Authorization: Basic $(echo -n 'waka_fb60903e-3fe8-4053-b437-5cac63fe8aeb') | base64"

