name: Test WakaTime API
on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    environment: waka-box
    steps:
      - name: Check WAKATIME_API_KEY
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          if [ -z "$WAKATIME_API_KEY" ]; then
            echo "WAKATIME_API_KEY is not set!"
          else
            echo "WAKATIME_API_KEY is set."
          fi

      - name: Make API Call
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          echo $WAKATIME_API_KEY | base64 > auth.txt
          curl -X GET "https://wakatime.com/api/v1/users/current/stats/last_7_days" \
            -H "Authorization: Basic $(cat auth.txt)"
          rm auth.txt
