name: Testing
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: waka-box
    steps:
      - uses: actions/checkout@master
      
      - name: Test WakaTime API (Last 7 Days)
        run: |
          encoded=$(echo -n "${{ secrets.WAKATIME_API_KEY }}" | base64)
          echo "Testing WakaTime API for last 7 days..."
          curl -s "https://wakatime.com/api/v1/users/current/stats/last_7_days" \
            -H "Authorization: Basic $encoded" | jq .

      - name: Test WakaTime API (Today)
        run: |
          encoded=$(echo -n "${{ secrets.WAKATIME_API_KEY }}" | base64)
          echo "Testing WakaTime API for today..."
          curl -s "https://wakatime.com/api/v1/users/current/summaries?range=today" \
            -H "Authorization: Basic $encoded" | jq .

      - name: Test WakaTime API (Status)
        run: |
          encoded=$(echo -n "${{ secrets.WAKATIME_API_KEY }}" | base64)
          echo "Testing WakaTime API status..."
          curl -s "https://wakatime.com/api/v1/users/current/status/all_time" \
            -H "Authorization: Basic $encoded" | jq .

      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
