name: Test WakaTime API
on:
  workflow_dispatch:
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check WAKATIME_API_KEY
        run: |
          if [ -z "${{ secrets.WAKATIME_API_KEY }}" ]; then
            echo "WAKATIME_API_KEY is not set!"
          else
            echo "WAKATIME_API_KEY is set."
          fi

      - name: Make API Call
        run: |
          curl -X GET "https://wakatime.com/api/v1/users/current/stats/last_7_days" \
          -H "Authorization: Basic $(echo -n '${{ secrets.WAKATIME_API_KEY }}': | base64)"
